### ISSUE TITLE
Not appearing in frontend

### ISSUE THREAD

**Issue by mwanaJumuiya** [llapgoch/magento-custom-payment-method#1]
I installed this module, enabled it in the backend but it's not appearing among enabled payment methods when one is checking out.

**Comment by llapgoch** [comment]
Hi, this is only an example module - it's just a starting point demo

**Comment by mwanaJumuiya** [comment]
Thanks, but am using it on the demo not live or production, trying to learn it. Wish it worked on demo as am now forced Google all over trying to figure out what code is not working. Thanks.
